### ISSUE TITLE
Implement An AMM Swap interface Component

### ISSUE THREAD

**Issue by Oshioke-Salaki** [horuslabsio/seamlessui#7]
Description:
Develop an  AMM Swap interface component as per the design provided in the [FIGMA FILE](https://www.figma.com/design/pL9HcD5saTR6TtMsZYyS7z/STARKNET-UI-KITS?node-id=0-1&node-type=canvas&t=gT1lFVCNijoXRGlC-0) along with all it’s variants. The component should have support for all available tokens within the Starknet ecosystem.

Requirements:

- Design: Follow the provided Figma design precisely for both light and dark mode. Ensure that the component is fully responsive across different screen sizes.
- Style Guide: Adhere strictly to the project’s existing style guide for consistency in UI and UX.
- Functionality: The component should be fully functional, allowing users to seamlessly switch networks.

After building the component, create a sub-route in the preview route for the component and display each of it’s variant for easy testing. 

Guidance:
There is an already implemented Connect Button component which can serve as a reference for styling, functionality and previewing.

Note:
No other external dependencies should be installed other than the ones already provided.

**Comment by petersdt** [comment]
h

**Comment by NueloSE** [comment]
h

**Comment by ShantelPeters** [comment]
Hello @Oshioke-Salaki please can I work on this issue ?

**Comment by martinvibes** [comment]
h

**Comment by CollinsC1O** [comment]
n

**Comment by dev-chinx** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by Ugo-X** [comment]
hello @Oshioke-Salaki  I would like to work on this.

# I will develop an AMM Swap interface component for Starknet as follows:

I will study the Figma design, focusing on all variants and both light/dark modes.

I will create a responsive React component using TypeScript and Tailwind CSS, adhering to the project's style guide.

I will implement state management for token selection, amount input, and network switching.

I will integrate the existing Connect Button and add functionality for all Starknet ecosystem tokens.

I will create component variants as per the Figma design, using React props for different states.

I will set up a preview sub-route to showcase all component variants for testing.

I will ensure the component works without additional external dependencies.

I will test thoroughly across different browsers and devices.

**Comment by Oshioke-Salaki** [comment]
Okay @Ugo-X i will give it to you 🚀

**Comment by Ugo-X** [comment]
> Okay @Ugo-X i will give it to you 🚀

alright ser, will get to it.

**Comment by Oshioke-Salaki** [comment]
Hello guys, everyone needs to apply for issues via, The OnlyDust Platform. So please do that and i will assign. Only applications done via OD will be considered.

**Comment by Ugo-X** [comment]
> Hello guys, everyone needs to apply for issues via, The OnlyDust Platform. So please do that and i will assign. Only applications done via OD will be considered.

done

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am a Full Stack Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects.  

With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space. 
 

 

### How I plan on tackling this issue

 
# I will develop an AMM Swap interface component for Starknet as follows: 

I will study the Figma design, focusing on all variants and both light/dark modes. 

  

I will create a responsive React component using TypeScript and Tailwind CSS, adhering to the project's style guide. 

  

I will implement state management for token selection, amount input, and network switching. 

  

I will integrate the existing Connect Button and add functionality for all Starknet ecosystem tokens. 

  

I will create component variants as per the Figma design, using React props for different states. 

  

I will set up a preview sub-route to showcase all component variants for testing. 

  

I will ensure the component works without additional external dependencies. 

  

I will test thoroughly across different browsers and devices.

**Comment by Ugo-X** [comment]
> Hello guys, everyone needs to apply for issues via, The OnlyDust Platform. So please do that and i will assign. Only applications done via OD will be considered.

done

**Comment by Jemiiah** [comment]
It’s showing crashed not working

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am a frontend engineer with over 5 years building scalable webapps.

### How I plan on tackling this issue
I will tackle this problem by:
- Creating a fully functional AMM swap interface component based on the design provided.
- Making sure this new component is responsive for all screen sizes
- Leveraging the existing UI library in the codebase to build this component.
- Adding the newly created component to the preview route for easy testing of all the variants created.
ETA: 48hrs

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hello @Oshioke-Salaki can I work on this

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
i am a frontend and blockchain developer with experience in the UI/UX.

### How I plan on tackling this issue
1. Design & Style: Implement the AMM Swap interface exactly as per the Figma file, using the existing style guide and the Connect Button component as a reference for consistency.
2. Functionality: Ensure full support for swapping all Starknet tokens and allow seamless network switching.
3. Responsiveness Make sure the component is responsive for all screen sizes.

4. Sub-Route Add a sub-route in the preview route to test all component variants.

5. No New Dependencies: Stick to the provided dependencies and avoid adding new ones.
